frame_info:
  foot_frame_ids:
    FL: 7644
    RL: 7064
    FR: 7433
    RR: 7276
  shoulder_frame_ids:
    FL: 7618
    RL: 7075
    FR: 7557
    RR: 7284
    # 5111
  # foot_frame_ids:
  #   FL: 19955
  #   RL: 9043
  #   FR: 20032
  #   RR: 22222
  # shoulder_frame_ids:
  #   FL: 4295
  #   RL: 4286
  #   FR: 1272
  #   RR: 22223
  foot_offset:
    FL: [0.05, -0.03, -0.0]
    RL: [0.0, -0.03, -0.0]
    FR: [0.05, 0.03, -0.02]
    RR: [0.0, 0.03, -0.0]
  shoulder_offset:
    FL: [0.0, 0.0, 0.0]
    RL: [0.0, 0.0, 0.1]
    FR: [0.0, 0.0, 0.0]
    RR: [0.0, 0.0, 0.1]