frame_info:
  foot_frame_ids:
    FL: 2538
    RL: 2503
    FR: 2540
    RR: 2541
  shoulder_frame_ids:
    FL: 2232
    RL: 2170
    FR: 2434
    RR: 2433
  foot_offset:
    FL: [0.072, 0.0, 0.0]
    RL: [0.0, 0.0, -0.108]
    FR: [0.072, 0.0, 0.0]
    RR: [0.0, 0.0, -0.108]