frame_info:
  foot_frame_ids:
    FL: "FFL"
    RL: "FRL"
    FR: "FFR"
    RR: "FRR"
  shoulder_frame_ids:
    FL: "SFL"
    RL: "SRL"
    FR: "SFR"
    RR: "SRR"
    # 5111
  # foot_frame_ids:
  #   FL: 19955
  #   RL: 9043
  #   FR: 20032
  #   RR: 22222
  # shoulder_frame_ids:
  #   FL: 4295
  #   RL: 4286
  #   FR: 1272
  #   RR: 22223
  foot_offset:
    FL: [0.0, -0.1, -0.15]
    RL: [0.0, -0.1, -0.15]
    FR: [-0.1, 0.1, -0.15]
    RR: [0.0, 0.1, -0.15]
  shoulder_offset:
    FL: [0.0, 0.0, -0.45]
    RL: [0.0, 0.0, -0.45]
    FR: [0.0, 0.0, -0.45]
    RR: [0.0, 0.0, -0.45]