frame_info:
  foot_frame_ids:
    FL: 2538
    RL: 2503
    FR: 2540
    RR: 2541
  shoulder_frame_ids:
    FL: 2232
    RL: 2170
    FR: 2434
    RR: 2433
  # foot_frame_ids:
  #   FL: 19955
  #   RL: 9043
  #   FR: 20032
  #   RR: 22222
  # shoulder_frame_ids:
  #   FL: 4295
  #   RL: 4286
  #   FR: 1272
  #   RR: 22223
  foot_offset:
    FL: [0.0, -0.15, -0.02]
    RL: [0.0, -0.15, -0.02]
    FR: [0.0, 0.15, -0.02]
    RR: [0.0, 0.15, -0.02]
  shoulder_offset:
    FL: [0.0, 0.0, 0.0]
    RL: [0.0, 0.0, 0.0]
    FR: [0.0, 0.0, 0.0]
    RR: [0.0, 0.0, 0.0]